/**
 * Expo config plugin — fits Android's autofill highlight to the app's fields.
 *
 * When autofill fills a field, Android paints the theme's
 * `android:autofilledHighlight` over the whole view: by default a translucent
 * yellow RECTANGLE. The sign-in and sign-up fields are pills (AuthScaffold:
 * 60 tall, radius 30), so the square yellow box stuck out past their rounded
 * ends. This swaps it for the same yellow as a pill. Android clamps a corner
 * radius to half the shorter side, so one huge radius gives an exact pill at
 * any field height.
 *
 * The highlight is theme-wide (Android has no per-view setting), so every
 * autofilled field gets the pill. The other fields that autofill can reach are
 * pills too, or (FormField) a borderless input inside its own box.
 *
 * Why a plugin: `android/` is generated by `expo prebuild` and gitignored, so
 * a hand edit there is lost on the next prebuild. See withArCoreApiKey.js.
 */
const fs = require("fs");
const path = require("path");
const { AndroidConfig, withAndroidStyles, withDangerousMod } = require("@expo/config-plugins");

const DRAWABLE = "autofill_highlight";

// Android's own colour for it (#4DFFEB3B, yellow at 30%), so it still reads
// as "filled in by autofill"; only the shape changes.
const DRAWABLE_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Autofill highlight as a pill, to fit the app's pill fields.
     Written by plugins/withAutofillHighlight.js. -->
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
  <solid android:color="#4DFFEB3B" />
  <corners android:radius="999dp" />
</shape>
`;

/**
 * The styles.xml edit, split out so it can be tested without a prebuild.
 * Overwrites an existing item, so running prebuild again doesn't duplicate it.
 *
 * @param styles the parsed styles.xml (cfg.modResults)
 * @returns the same styles, with AppTheme's autofill highlight set
 */
function applyAutofillHighlight(styles) {
  return AndroidConfig.Styles.assignStylesValue(styles, {
    add: true,
    parent: AndroidConfig.Styles.getAppThemeGroup(),
    name: "android:autofilledHighlight",
    value: `@drawable/${DRAWABLE}`,
    // The attribute exists from Android 8 (API 26); older versions ignore it.
    targetApi: "26",
  });
}

function withAutofillHighlight(config) {
  config = withDangerousMod(config, [
    "android",
    async (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, "app", "src", "main", "res", "drawable");
      await fs.promises.mkdir(dir, { recursive: true });
      await fs.promises.writeFile(path.join(dir, `${DRAWABLE}.xml`), DRAWABLE_XML);
      return cfg;
    },
  ]);
  return withAndroidStyles(config, (cfg) => {
    cfg.modResults = applyAutofillHighlight(cfg.modResults);
    return cfg;
  });
}

module.exports = withAutofillHighlight;
module.exports.applyAutofillHighlight = applyAutofillHighlight;
module.exports.DRAWABLE_XML = DRAWABLE_XML;
