/**
 * Expo config plugin — injects the ARCore API key into AndroidManifest.xml.
 *
 * The ARCore Geospatial API authenticates against a Google Cloud project, and
 * on Android that key has to be declared in the manifest as
 * `com.google.android.ar.API_KEY`. Without it, enabling geospatial mode fails
 * at runtime with an authentication error.
 *
 * Why a plugin rather than editing the manifest directly: `android/` is in
 * .gitignore — it's generated by `expo prebuild` — so any hand edit there is
 * lost on the next prebuild and never reaches the repository. This runs as part
 * of prebuild, so the key is applied every time the project is generated.
 *
 * The key is read from the ARCORE_API_KEY environment variable and is
 * deliberately NOT written into app.json, which IS committed. Set it in .env
 * for local builds and as an EAS secret for cloud builds:
 *
 *     eas secret:create --scope project --name ARCORE_API_KEY --value <key>
 *
 * If the variable is missing the plugin is a no-op with a warning, so a build
 * without the key still succeeds — the app just falls back to the existing
 * plane-based AR placement instead of crashing.
 */
const { withAndroidManifest } = require("@expo/config-plugins");

const META_NAME = "com.google.android.ar.API_KEY";

/**
 * The actual manifest edit, split out from the plugin wrapper so it can be
 * tested without running a full prebuild.
 *
 * @param manifest the parsed AndroidManifest (cfg.modResults.manifest)
 * @param key      the ARCore API key, or a falsy value to make this a no-op
 * @returns the same manifest, mutated
 */
function applyArCoreKey(manifest, key) {
  if (!key) {
    console.warn(
      "[withArCoreApiKey] ARCORE_API_KEY is not set — skipping. " +
        "ARCore Geospatial will be unavailable and the app will use plane-based AR placement."
    );
    return manifest;
  }

  const app = manifest?.application?.[0];
  if (!app) {
    console.warn("[withArCoreApiKey] No <application> node found in the manifest — skipping.");
    return manifest;
  }

  // Replace rather than append: a duplicate meta-data name is a manifest merge
  // failure, and prebuild may run over an already-patched manifest.
  app["meta-data"] = (app["meta-data"] || []).filter(
    (m) => m?.$?.["android:name"] !== META_NAME
  );

  app["meta-data"].push({
    $: { "android:name": META_NAME, "android:value": key },
  });

  return manifest;
}

function withArCoreApiKey(config) {
  return withAndroidManifest(config, (cfg) => {
    applyArCoreKey(cfg.modResults.manifest, process.env.ARCORE_API_KEY);
    return cfg;
  });
}

module.exports = withArCoreApiKey;
module.exports.applyArCoreKey = applyArCoreKey;
module.exports.META_NAME = META_NAME;
